stacks.widget_entity_type.*:
  type: config_entity
  label: 'Widget Entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    plugin:
      type: string
      label: 'Plugin'
